name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install esy
        run: npm install -g esy
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: ~/.esy
          key: ${{ runner.os}}-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.os}}-
      - run: esy install 
      - run: esy dune build @all .
      - run: esy dune runtest
        
